// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: archway/callback/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgRequestCallback is the Msg/RequestCallback request type.
type MsgRequestCallback struct {
	// sender is the address who is requesting the callback (bech32 encoded)
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// contract_address is the address of the contract which is requesting the callback (bech32 encoded)
	ContractAddress string `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	// job_id is an identifier the callback requestor can pass in to identify the callback when it happens
	JobId uint64 `protobuf:"varint,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// callback_height is the height at which the callback is executed.
	CallbackHeight int64 `protobuf:"varint,4,opt,name=callback_height,json=callbackHeight,proto3" json:"callback_height,omitempty"`
	// fees is the amount of fees being paid to register the contract
	Fees types.Coin `protobuf:"bytes,5,opt,name=fees,proto3" json:"fees"`
}

func (m *MsgRequestCallback) Reset()         { *m = MsgRequestCallback{} }
func (m *MsgRequestCallback) String() string { return proto.CompactTextString(m) }
func (*MsgRequestCallback) ProtoMessage()    {}
func (*MsgRequestCallback) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9a16d5bd27202f4, []int{0}
}
func (m *MsgRequestCallback) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRequestCallback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRequestCallback.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRequestCallback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRequestCallback.Merge(m, src)
}
func (m *MsgRequestCallback) XXX_Size() int {
	return m.Size()
}
func (m *MsgRequestCallback) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRequestCallback.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRequestCallback proto.InternalMessageInfo

func (m *MsgRequestCallback) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgRequestCallback) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *MsgRequestCallback) GetJobId() uint64 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *MsgRequestCallback) GetCallbackHeight() int64 {
	if m != nil {
		return m.CallbackHeight
	}
	return 0
}

func (m *MsgRequestCallback) GetFees() types.Coin {
	if m != nil {
		return m.Fees
	}
	return types.Coin{}
}

// MsgRequestCallbackResponse defines the response structure for executing a MsgRequestCallback message.
type MsgRequestCallbackResponse struct {
}

func (m *MsgRequestCallbackResponse) Reset()         { *m = MsgRequestCallbackResponse{} }
func (m *MsgRequestCallbackResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRequestCallbackResponse) ProtoMessage()    {}
func (*MsgRequestCallbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9a16d5bd27202f4, []int{1}
}
func (m *MsgRequestCallbackResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRequestCallbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRequestCallbackResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRequestCallbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRequestCallbackResponse.Merge(m, src)
}
func (m *MsgRequestCallbackResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRequestCallbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRequestCallbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRequestCallbackResponse proto.InternalMessageInfo

// MsgCancelCallback is the Msg/CancelCallback request type.
type MsgCancelCallback struct {
	// sender is the address of the contract which is cancelling the callback (bech32 encoded)
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// contract_address is the address of the contract (bech32 encoded)
	ContractAddress string `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	// job_id is an identifier the callback requestor had passed during registration of the callback
	JobId uint64 `protobuf:"varint,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// callback_height is the height at which the callback requestor had registered the callback
	CallbackHeight int64 `protobuf:"varint,4,opt,name=callback_height,json=callbackHeight,proto3" json:"callback_height,omitempty"`
}

func (m *MsgCancelCallback) Reset()         { *m = MsgCancelCallback{} }
func (m *MsgCancelCallback) String() string { return proto.CompactTextString(m) }
func (*MsgCancelCallback) ProtoMessage()    {}
func (*MsgCancelCallback) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9a16d5bd27202f4, []int{2}
}
func (m *MsgCancelCallback) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelCallback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelCallback.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelCallback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelCallback.Merge(m, src)
}
func (m *MsgCancelCallback) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelCallback) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelCallback.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelCallback proto.InternalMessageInfo

func (m *MsgCancelCallback) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgCancelCallback) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *MsgCancelCallback) GetJobId() uint64 {
	if m != nil {
		return m.JobId
	}
	return 0
}

func (m *MsgCancelCallback) GetCallbackHeight() int64 {
	if m != nil {
		return m.CallbackHeight
	}
	return 0
}

// MsgCancelCallbackResponse defines the response structure for executing a MsgCancelCallback message.
type MsgCancelCallbackResponse struct {
	// refund is the amount of fees being refunded due to the cancellation of the callback
	Refund types.Coin `protobuf:"bytes,1,opt,name=refund,proto3" json:"refund"`
}

func (m *MsgCancelCallbackResponse) Reset()         { *m = MsgCancelCallbackResponse{} }
func (m *MsgCancelCallbackResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCancelCallbackResponse) ProtoMessage()    {}
func (*MsgCancelCallbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9a16d5bd27202f4, []int{3}
}
func (m *MsgCancelCallbackResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelCallbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelCallbackResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelCallbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelCallbackResponse.Merge(m, src)
}
func (m *MsgCancelCallbackResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelCallbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelCallbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelCallbackResponse proto.InternalMessageInfo

func (m *MsgCancelCallbackResponse) GetRefund() types.Coin {
	if m != nil {
		return m.Refund
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*MsgRequestCallback)(nil), "archway.callback.v1.MsgRequestCallback")
	proto.RegisterType((*MsgRequestCallbackResponse)(nil), "archway.callback.v1.MsgRequestCallbackResponse")
	proto.RegisterType((*MsgCancelCallback)(nil), "archway.callback.v1.MsgCancelCallback")
	proto.RegisterType((*MsgCancelCallbackResponse)(nil), "archway.callback.v1.MsgCancelCallbackResponse")
}

func init() { proto.RegisterFile("archway/callback/v1/tx.proto", fileDescriptor_d9a16d5bd27202f4) }

var fileDescriptor_d9a16d5bd27202f4 = []byte{
	// 463 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x93, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0x6b, 0xda, 0x55, 0xc2, 0x93, 0x56, 0x08, 0xff, 0xb2, 0x68, 0x0a, 0x55, 0x0f, 0xac,
	0x20, 0x61, 0xab, 0x9b, 0x10, 0x12, 0x37, 0xd6, 0x0b, 0x1c, 0x2a, 0xa4, 0x88, 0x13, 0x97, 0xca,
	0x71, 0x3c, 0x27, 0x5b, 0x62, 0x87, 0xbc, 0x6e, 0xd7, 0x72, 0xe4, 0x13, 0xf0, 0x1d, 0xf8, 0x02,
	0x7c, 0x8c, 0x1d, 0x77, 0x04, 0x09, 0x21, 0xd4, 0x1e, 0xf8, 0x1a, 0xa8, 0xa9, 0x33, 0xb4, 0xb5,
	0x48, 0x3d, 0xee, 0x96, 0xbc, 0xcf, 0x4f, 0x79, 0x9f, 0xe7, 0x89, 0x8d, 0xf7, 0x58, 0xc1, 0xe3,
	0x33, 0x36, 0xa5, 0x9c, 0xa5, 0x69, 0xc8, 0xf8, 0x29, 0x1d, 0xf7, 0xa8, 0x99, 0x90, 0xbc, 0xd0,
	0x46, 0x3b, 0xf7, 0xac, 0x4a, 0x2a, 0x95, 0x8c, 0x7b, 0xde, 0x7d, 0xa9, 0xa5, 0x2e, 0x75, 0xba,
	0x78, 0x5a, 0xa2, 0x9e, 0xcf, 0x35, 0x64, 0x1a, 0x68, 0xc8, 0x40, 0xd0, 0x71, 0x2f, 0x14, 0x86,
	0xf5, 0x28, 0xd7, 0x89, 0xb2, 0xfa, 0x23, 0xab, 0x67, 0x20, 0x17, 0x2b, 0x32, 0x90, 0x56, 0xe8,
	0xac, 0x73, 0x70, 0xb9, 0xaf, 0x64, 0x3a, 0x3f, 0x10, 0x76, 0x06, 0x20, 0x03, 0xf1, 0x71, 0x24,
	0xc0, 0xf4, 0xad, 0xe8, 0x3c, 0xc4, 0x4d, 0x10, 0x2a, 0x12, 0x85, 0x8b, 0xda, 0xa8, 0x7b, 0x3b,
	0xb0, 0x6f, 0xce, 0x53, 0x7c, 0x87, 0x6b, 0x65, 0x0a, 0xc6, 0xcd, 0x90, 0x45, 0x51, 0x21, 0x00,
	0xdc, 0x5b, 0x25, 0xd1, 0xaa, 0xe6, 0xaf, 0x97, 0x63, 0xe7, 0x01, 0x6e, 0x9e, 0xe8, 0x70, 0x98,
	0x44, 0x6e, 0xbd, 0x8d, 0xba, 0x8d, 0x60, 0xeb, 0x44, 0x87, 0x6f, 0x23, 0x67, 0x1f, 0xb7, 0x2a,
	0x0b, 0xc3, 0x58, 0x24, 0x32, 0x36, 0x6e, 0xa3, 0x8d, 0xba, 0xf5, 0x60, 0xa7, 0x1a, 0xbf, 0x29,
	0xa7, 0xce, 0x21, 0x6e, 0x1c, 0x0b, 0x01, 0xee, 0x56, 0x1b, 0x75, 0xb7, 0x0f, 0x76, 0xc9, 0x32,
	0x25, 0x59, 0xb4, 0x40, 0x6c, 0x0b, 0xa4, 0xaf, 0x13, 0x75, 0xd4, 0x38, 0xff, 0xf5, 0xb8, 0x16,
	0x94, 0xf0, 0xab, 0xed, 0xcf, 0x7f, 0xbe, 0x3d, 0xb3, 0x66, 0x3b, 0x7b, 0xd8, 0x5b, 0x8d, 0x16,
	0x08, 0xc8, 0xb5, 0x02, 0xd1, 0xf9, 0x8a, 0xf0, 0xdd, 0x01, 0xc8, 0x3e, 0x53, 0x5c, 0xa4, 0x37,
	0x28, 0xf8, 0xd5, 0x0c, 0xef, 0xf1, 0xee, 0x8a, 0xc9, 0x2a, 0x82, 0xf3, 0x12, 0x37, 0x0b, 0x71,
	0x3c, 0x52, 0x51, 0x69, 0x76, 0x83, 0x92, 0x2c, 0x7e, 0xf0, 0x13, 0xe1, 0xfa, 0x00, 0xa4, 0x73,
	0x8a, 0x5b, 0xd7, 0xff, 0xfc, 0x3e, 0x59, 0x73, 0x32, 0xc9, 0x6a, 0x8f, 0x1e, 0xdd, 0x10, 0xbc,
	0x74, 0x1b, 0xe3, 0x9d, 0x6b, 0x65, 0x3f, 0xf9, 0xdf, 0x27, 0xae, 0x72, 0x1e, 0xd9, 0x8c, 0xab,
	0x36, 0x1d, 0xbd, 0x3b, 0x9f, 0xf9, 0xe8, 0x62, 0xe6, 0xa3, 0xdf, 0x33, 0x1f, 0x7d, 0x99, 0xfb,
	0xb5, 0x8b, 0xb9, 0x5f, 0xfb, 0x3e, 0xf7, 0x6b, 0x1f, 0x5e, 0xc8, 0xc4, 0xc4, 0xa3, 0x90, 0x70,
	0x9d, 0xd1, 0x68, 0x9a, 0x09, 0x05, 0x89, 0x56, 0x93, 0xe9, 0x27, 0x5a, 0xe8, 0x34, 0x65, 0x79,
	0xfe, 0xfc, 0x8c, 0x41, 0x46, 0x27, 0xff, 0x6e, 0x8c, 0x99, 0xe6, 0x02, 0xc2, 0x66, 0x79, 0x59,
	0x0e, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x83, 0xde, 0xf7, 0x24, 0xd4, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// RequestCallback defines a message for registering a callback at a specific height by a given contract
	RequestCallback(ctx context.Context, in *MsgRequestCallback, opts ...grpc.CallOption) (*MsgRequestCallbackResponse, error)
	// CancelCallback defines a message for cancelling an existing callback
	CancelCallback(ctx context.Context, in *MsgCancelCallback, opts ...grpc.CallOption) (*MsgCancelCallbackResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RequestCallback(ctx context.Context, in *MsgRequestCallback, opts ...grpc.CallOption) (*MsgRequestCallbackResponse, error) {
	out := new(MsgRequestCallbackResponse)
	err := c.cc.Invoke(ctx, "/archway.callback.v1.Msg/RequestCallback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CancelCallback(ctx context.Context, in *MsgCancelCallback, opts ...grpc.CallOption) (*MsgCancelCallbackResponse, error) {
	out := new(MsgCancelCallbackResponse)
	err := c.cc.Invoke(ctx, "/archway.callback.v1.Msg/CancelCallback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// RequestCallback defines a message for registering a callback at a specific height by a given contract
	RequestCallback(context.Context, *MsgRequestCallback) (*MsgRequestCallbackResponse, error)
	// CancelCallback defines a message for cancelling an existing callback
	CancelCallback(context.Context, *MsgCancelCallback) (*MsgCancelCallbackResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RequestCallback(ctx context.Context, req *MsgRequestCallback) (*MsgRequestCallbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestCallback not implemented")
}
func (*UnimplementedMsgServer) CancelCallback(ctx context.Context, req *MsgCancelCallback) (*MsgCancelCallbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelCallback not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RequestCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRequestCallback)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RequestCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/archway.callback.v1.Msg/RequestCallback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RequestCallback(ctx, req.(*MsgRequestCallback))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CancelCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCancelCallback)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CancelCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/archway.callback.v1.Msg/CancelCallback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CancelCallback(ctx, req.(*MsgCancelCallback))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "archway.callback.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestCallback",
			Handler:    _Msg_RequestCallback_Handler,
		},
		{
			MethodName: "CancelCallback",
			Handler:    _Msg_CancelCallback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "archway/callback/v1/tx.proto",
}

func (m *MsgRequestCallback) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRequestCallback) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRequestCallback) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Fees.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.CallbackHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.CallbackHeight))
		i--
		dAtA[i] = 0x20
	}
	if m.JobId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.JobId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRequestCallbackResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRequestCallbackResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRequestCallbackResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCancelCallback) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelCallback) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelCallback) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CallbackHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.CallbackHeight))
		i--
		dAtA[i] = 0x20
	}
	if m.JobId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.JobId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCancelCallbackResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelCallbackResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelCallbackResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Refund.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRequestCallback) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.JobId != 0 {
		n += 1 + sovTx(uint64(m.JobId))
	}
	if m.CallbackHeight != 0 {
		n += 1 + sovTx(uint64(m.CallbackHeight))
	}
	l = m.Fees.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgRequestCallbackResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCancelCallback) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.JobId != 0 {
		n += 1 + sovTx(uint64(m.JobId))
	}
	if m.CallbackHeight != 0 {
		n += 1 + sovTx(uint64(m.CallbackHeight))
	}
	return n
}

func (m *MsgCancelCallbackResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Refund.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRequestCallback) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRequestCallback: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRequestCallback: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field JobId", wireType)
			}
			m.JobId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.JobId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallbackHeight", wireType)
			}
			m.CallbackHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CallbackHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fees", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Fees.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRequestCallbackResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRequestCallbackResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRequestCallbackResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelCallback) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelCallback: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelCallback: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field JobId", wireType)
			}
			m.JobId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.JobId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallbackHeight", wireType)
			}
			m.CallbackHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CallbackHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelCallbackResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelCallbackResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelCallbackResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Refund", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Refund.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
