// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: archway/cwerrors/v1/params.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the set of parameters for the cwerrors module.
type Params struct {
	// error_stored_time is the block height until which error is stored
	ErrorStoredTime int64 `protobuf:"varint,1,opt,name=error_stored_time,json=errorStoredTime,proto3" json:"error_stored_time,omitempty"`
	// subsciption_fee is the fee required to subscribe to error callbacks
	SubscriptionFee types.Coin `protobuf:"bytes,2,opt,name=subscription_fee,json=subscriptionFee,proto3" json:"subscription_fee"`
	// subscription_period is the period for which the subscription is valid
	SubscriptionPeriod int64 `protobuf:"varint,3,opt,name=subscription_period,json=subscriptionPeriod,proto3" json:"subscription_period,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_178d89d427939559, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetErrorStoredTime() int64 {
	if m != nil {
		return m.ErrorStoredTime
	}
	return 0
}

func (m *Params) GetSubscriptionFee() types.Coin {
	if m != nil {
		return m.SubscriptionFee
	}
	return types.Coin{}
}

func (m *Params) GetSubscriptionPeriod() int64 {
	if m != nil {
		return m.SubscriptionPeriod
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "archway.cwerrors.v1.Params")
}

func init() { proto.RegisterFile("archway/cwerrors/v1/params.proto", fileDescriptor_178d89d427939559) }

var fileDescriptor_178d89d427939559 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcd, 0x4e, 0x02, 0x31,
	0x14, 0x85, 0xa7, 0x62, 0x58, 0x8c, 0x0b, 0x74, 0x70, 0x81, 0x2c, 0x2a, 0x71, 0x45, 0x4c, 0x6c,
	0x33, 0x1a, 0x5f, 0x00, 0x13, 0x17, 0x6e, 0x24, 0xe8, 0xca, 0x0d, 0xe9, 0x94, 0x2b, 0x34, 0xa1,
	0x73, 0x9b, 0xb6, 0xfc, 0x8c, 0x4f, 0xe1, 0xab, 0xf8, 0x16, 0x2c, 0x59, 0xba, 0x32, 0x86, 0x79,
	0x11, 0x43, 0x07, 0x23, 0xee, 0x9a, 0x7e, 0xe7, 0x9e, 0x2f, 0x39, 0x71, 0x47, 0x58, 0x39, 0x59,
	0x88, 0x82, 0xcb, 0x05, 0x58, 0x8b, 0xd6, 0xf1, 0x79, 0xca, 0x8d, 0xb0, 0x42, 0x3b, 0x66, 0x2c,
	0x7a, 0x4c, 0x9a, 0xbb, 0x04, 0xfb, 0x4d, 0xb0, 0x79, 0xda, 0x3e, 0x1d, 0xe3, 0x18, 0x03, 0xe7,
	0xdb, 0x57, 0x15, 0x6d, 0x53, 0x89, 0x4e, 0xa3, 0xe3, 0x99, 0x70, 0xc0, 0xe7, 0x69, 0x06, 0x5e,
	0xa4, 0x5c, 0xa2, 0xca, 0x2b, 0x7e, 0xf1, 0x41, 0xe2, 0x7a, 0x3f, 0x74, 0x27, 0x97, 0xf1, 0x49,
	0x68, 0x1b, 0x3a, 0x8f, 0x16, 0x46, 0x43, 0xaf, 0x34, 0xb4, 0x48, 0x87, 0x74, 0x6b, 0x83, 0x46,
	0x00, 0x4f, 0xe1, 0xff, 0x59, 0x69, 0x48, 0x1e, 0xe2, 0x63, 0x37, 0xcb, 0x9c, 0xb4, 0xca, 0x78,
	0x85, 0xf9, 0xf0, 0x15, 0xa0, 0x75, 0xd0, 0x21, 0xdd, 0xa3, 0xeb, 0x33, 0x56, 0x19, 0xd9, 0xd6,
	0xc8, 0x76, 0x46, 0x76, 0x87, 0x2a, 0xef, 0x1d, 0xae, 0xbe, 0xce, 0xa3, 0x41, 0x63, 0xff, 0xf0,
	0x1e, 0x20, 0xe1, 0x71, 0xf3, 0x5f, 0x97, 0x01, 0xab, 0x70, 0xd4, 0xaa, 0x05, 0x73, 0xb2, 0x8f,
	0xfa, 0x81, 0xf4, 0x1e, 0x57, 0x1b, 0x4a, 0xd6, 0x1b, 0x4a, 0xbe, 0x37, 0x94, 0xbc, 0x97, 0x34,
	0x5a, 0x97, 0x34, 0xfa, 0x2c, 0x69, 0xf4, 0x72, 0x3b, 0x56, 0x7e, 0x32, 0xcb, 0x98, 0x44, 0xcd,
	0x47, 0x85, 0x86, 0xdc, 0x29, 0xcc, 0x97, 0xc5, 0x1b, 0xb7, 0x38, 0x9d, 0x0a, 0x63, 0xae, 0x16,
	0xc2, 0x69, 0xbe, 0xfc, 0x5b, 0xd6, 0x17, 0x06, 0x5c, 0x56, 0x0f, 0x5b, 0xdc, 0xfc, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xe7, 0x5f, 0xf8, 0x68, 0x7a, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SubscriptionPeriod != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.SubscriptionPeriod))
		i--
		dAtA[i] = 0x18
	}
	{
		size, err := m.SubscriptionFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.ErrorStoredTime != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ErrorStoredTime))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ErrorStoredTime != 0 {
		n += 1 + sovParams(uint64(m.ErrorStoredTime))
	}
	l = m.SubscriptionFee.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.SubscriptionPeriod != 0 {
		n += 1 + sovParams(uint64(m.SubscriptionPeriod))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrorStoredTime", wireType)
			}
			m.ErrorStoredTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ErrorStoredTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubscriptionFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SubscriptionFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubscriptionPeriod", wireType)
			}
			m.SubscriptionPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubscriptionPeriod |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
