// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: archway/cwerrors/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgSubscribeToError is the Msg/SubscribeToError request type.
type MsgSubscribeToError struct {
	// sender is the address of who is registering the contarcts for callback on
	// error
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// contract is the address of the contract that will be called on error
	ContractAddress string `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	// fee is the subscription fee for the feature (current no fee is charged for
	// this feature)
	Fee types.Coin `protobuf:"bytes,3,opt,name=fee,proto3" json:"fee"`
}

func (m *MsgSubscribeToError) Reset()         { *m = MsgSubscribeToError{} }
func (m *MsgSubscribeToError) String() string { return proto.CompactTextString(m) }
func (*MsgSubscribeToError) ProtoMessage()    {}
func (*MsgSubscribeToError) Descriptor() ([]byte, []int) {
	return fileDescriptor_f833e7f9e8fbc63c, []int{0}
}
func (m *MsgSubscribeToError) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubscribeToError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubscribeToError.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubscribeToError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubscribeToError.Merge(m, src)
}
func (m *MsgSubscribeToError) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubscribeToError) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubscribeToError.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubscribeToError proto.InternalMessageInfo

func (m *MsgSubscribeToError) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgSubscribeToError) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *MsgSubscribeToError) GetFee() types.Coin {
	if m != nil {
		return m.Fee
	}
	return types.Coin{}
}

// MsgSubscribeToErrorResponse defines the response structure for executing a
// MsgSubscribeToError message.
type MsgSubscribeToErrorResponse struct {
	// subscription_valid_till is the block height till which the subscription is
	// valid
	SubscriptionValidTill int64 `protobuf:"varint,1,opt,name=subscription_valid_till,json=subscriptionValidTill,proto3" json:"subscription_valid_till,omitempty"`
}

func (m *MsgSubscribeToErrorResponse) Reset()         { *m = MsgSubscribeToErrorResponse{} }
func (m *MsgSubscribeToErrorResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubscribeToErrorResponse) ProtoMessage()    {}
func (*MsgSubscribeToErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f833e7f9e8fbc63c, []int{1}
}
func (m *MsgSubscribeToErrorResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubscribeToErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubscribeToErrorResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubscribeToErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubscribeToErrorResponse.Merge(m, src)
}
func (m *MsgSubscribeToErrorResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubscribeToErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubscribeToErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubscribeToErrorResponse proto.InternalMessageInfo

func (m *MsgSubscribeToErrorResponse) GetSubscriptionValidTill() int64 {
	if m != nil {
		return m.SubscriptionValidTill
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgSubscribeToError)(nil), "archway.cwerrors.v1.MsgSubscribeToError")
	proto.RegisterType((*MsgSubscribeToErrorResponse)(nil), "archway.cwerrors.v1.MsgSubscribeToErrorResponse")
}

func init() { proto.RegisterFile("archway/cwerrors/v1/tx.proto", fileDescriptor_f833e7f9e8fbc63c) }

var fileDescriptor_f833e7f9e8fbc63c = []byte{
	// 382 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xbf, 0xae, 0xd3, 0x30,
	0x14, 0x87, 0x13, 0x82, 0xae, 0x84, 0xef, 0xc0, 0x55, 0x0a, 0xb4, 0x14, 0x14, 0xaa, 0x4e, 0x05,
	0x09, 0x9b, 0x14, 0xc1, 0xc0, 0x46, 0x11, 0x63, 0x85, 0x14, 0x0a, 0x03, 0x4b, 0xe5, 0x38, 0x26,
	0xb5, 0x94, 0xf8, 0x44, 0x3e, 0x6e, 0xda, 0x30, 0xf2, 0x04, 0x8c, 0x3c, 0x06, 0x8f, 0xd1, 0xb1,
	0x23, 0x13, 0x42, 0xed, 0xc0, 0x6b, 0xa0, 0xfc, 0xa9, 0x40, 0xa2, 0x03, 0x9b, 0x7d, 0xbe, 0x9f,
	0x7c, 0x3e, 0xdb, 0x87, 0xdc, 0xe7, 0x46, 0xac, 0x36, 0xbc, 0x62, 0x62, 0x23, 0x8d, 0x01, 0x83,
	0xac, 0x0c, 0x99, 0xdd, 0xd2, 0xc2, 0x80, 0x05, 0xbf, 0xd7, 0x51, 0x7a, 0xa2, 0xb4, 0x0c, 0x87,
	0xb7, 0x52, 0x48, 0xa1, 0xe1, 0xac, 0x5e, 0xb5, 0xd1, 0x61, 0x5f, 0x00, 0xe6, 0x80, 0x2c, 0xc7,
	0xb4, 0x3e, 0x22, 0xc7, 0xb4, 0x03, 0x41, 0x07, 0x62, 0x8e, 0x92, 0x95, 0x61, 0x2c, 0x2d, 0x0f,
	0x99, 0x00, 0xa5, 0x5b, 0x3e, 0xfe, 0xea, 0x92, 0xde, 0x1c, 0xd3, 0xb7, 0xeb, 0x18, 0x85, 0x51,
	0xb1, 0x5c, 0xc0, 0xeb, 0xba, 0x95, 0x7f, 0x87, 0x5c, 0xa0, 0xd4, 0x89, 0x34, 0x03, 0x77, 0xe4,
	0x4e, 0x6e, 0x44, 0xdd, 0xce, 0x7f, 0x48, 0xae, 0x04, 0x68, 0x6b, 0xb8, 0xb0, 0x4b, 0x9e, 0x24,
	0x46, 0x22, 0x0e, 0xae, 0x35, 0x89, 0x9b, 0xa7, 0xfa, 0xcb, 0xb6, 0xec, 0x87, 0xc4, 0xfb, 0x28,
	0xe5, 0xc0, 0x1b, 0xb9, 0x93, 0xcb, 0xe9, 0x5d, 0xda, 0x8a, 0xd0, 0x5a, 0x84, 0x76, 0x22, 0xf4,
	0x15, 0x28, 0x3d, 0xbb, 0xbe, 0xfb, 0xf1, 0xc0, 0x89, 0xea, 0xec, 0x8b, 0xcb, 0xcf, 0xbf, 0xbe,
	0x3d, 0xea, 0x5a, 0x8d, 0xdf, 0x91, 0x7b, 0x67, 0xcc, 0x22, 0x89, 0x05, 0x68, 0x94, 0xfe, 0x73,
	0xd2, 0xc7, 0x96, 0x15, 0x56, 0x81, 0x5e, 0x96, 0x3c, 0x53, 0xc9, 0xd2, 0xaa, 0x2c, 0x6b, 0x94,
	0xbd, 0xe8, 0xf6, 0xdf, 0xf8, 0x7d, 0x4d, 0x17, 0x2a, 0xcb, 0xa6, 0x6b, 0xe2, 0xcd, 0x31, 0xf5,
	0x35, 0xb9, 0xfa, 0xe7, 0xd2, 0x13, 0x7a, 0xe6, 0xc5, 0xe9, 0x19, 0x89, 0xe1, 0x93, 0xff, 0x4d,
	0x9e, 0x74, 0x67, 0x6f, 0x76, 0x87, 0xc0, 0xdd, 0x1f, 0x02, 0xf7, 0xe7, 0x21, 0x70, 0xbf, 0x1c,
	0x03, 0x67, 0x7f, 0x0c, 0x9c, 0xef, 0xc7, 0xc0, 0xf9, 0xf0, 0x2c, 0x55, 0x76, 0xb5, 0x8e, 0xa9,
	0x80, 0x9c, 0x25, 0x55, 0x2e, 0x35, 0x2a, 0xd0, 0xdb, 0xea, 0x13, 0x33, 0x90, 0x65, 0xbc, 0x28,
	0x1e, 0x6f, 0x38, 0xe6, 0x6c, 0xfb, 0x67, 0x46, 0x6c, 0x55, 0x48, 0x8c, 0x2f, 0x9a, 0x0f, 0x7c,
	0xfa, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x63, 0x52, 0x8a, 0x1b, 0x44, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// SubscribeToError defines an operation which will register a contract for a
	// sudo callback on errors
	SubscribeToError(ctx context.Context, in *MsgSubscribeToError, opts ...grpc.CallOption) (*MsgSubscribeToErrorResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SubscribeToError(ctx context.Context, in *MsgSubscribeToError, opts ...grpc.CallOption) (*MsgSubscribeToErrorResponse, error) {
	out := new(MsgSubscribeToErrorResponse)
	err := c.cc.Invoke(ctx, "/archway.cwerrors.v1.Msg/SubscribeToError", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// SubscribeToError defines an operation which will register a contract for a
	// sudo callback on errors
	SubscribeToError(context.Context, *MsgSubscribeToError) (*MsgSubscribeToErrorResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SubscribeToError(ctx context.Context, req *MsgSubscribeToError) (*MsgSubscribeToErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubscribeToError not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SubscribeToError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubscribeToError)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubscribeToError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/archway.cwerrors.v1.Msg/SubscribeToError",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubscribeToError(ctx, req.(*MsgSubscribeToError))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "archway.cwerrors.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubscribeToError",
			Handler:    _Msg_SubscribeToError_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "archway/cwerrors/v1/tx.proto",
}

func (m *MsgSubscribeToError) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubscribeToError) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubscribeToError) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Fee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubscribeToErrorResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubscribeToErrorResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubscribeToErrorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SubscriptionValidTill != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SubscriptionValidTill))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSubscribeToError) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Fee.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgSubscribeToErrorResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SubscriptionValidTill != 0 {
		n += 1 + sovTx(uint64(m.SubscriptionValidTill))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSubscribeToError) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubscribeToError: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubscribeToError: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Fee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubscribeToErrorResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubscribeToErrorResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubscribeToErrorResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubscriptionValidTill", wireType)
			}
			m.SubscriptionValidTill = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SubscriptionValidTill |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
