// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: aib/cron/v1beta1/cron.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type WhitelistedContract struct {
	GameId          uint64 `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	SecurityAddress string `protobuf:"bytes,2,opt,name=security_address,json=securityAddress,proto3" json:"security_address,omitempty"`
	ContractAdmin   string `protobuf:"bytes,3,opt,name=contract_admin,json=contractAdmin,proto3" json:"contract_admin,omitempty"`
	GameName        string `protobuf:"bytes,4,opt,name=game_name,json=gameName,proto3" json:"game_name,omitempty"`
	ContractAddress string `protobuf:"bytes,5,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	GameType        uint64 `protobuf:"varint,6,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`
}

func (m *WhitelistedContract) Reset()         { *m = WhitelistedContract{} }
func (m *WhitelistedContract) String() string { return proto.CompactTextString(m) }
func (*WhitelistedContract) ProtoMessage()    {}
func (*WhitelistedContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c83358d263c9e57, []int{0}
}
func (m *WhitelistedContract) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WhitelistedContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WhitelistedContract.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WhitelistedContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhitelistedContract.Merge(m, src)
}
func (m *WhitelistedContract) XXX_Size() int {
	return m.Size()
}
func (m *WhitelistedContract) XXX_DiscardUnknown() {
	xxx_messageInfo_WhitelistedContract.DiscardUnknown(m)
}

var xxx_messageInfo_WhitelistedContract proto.InternalMessageInfo

func (m *WhitelistedContract) GetGameId() uint64 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *WhitelistedContract) GetSecurityAddress() string {
	if m != nil {
		return m.SecurityAddress
	}
	return ""
}

func (m *WhitelistedContract) GetContractAdmin() string {
	if m != nil {
		return m.ContractAdmin
	}
	return ""
}

func (m *WhitelistedContract) GetGameName() string {
	if m != nil {
		return m.GameName
	}
	return ""
}

func (m *WhitelistedContract) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *WhitelistedContract) GetGameType() uint64 {
	if m != nil {
		return m.GameType
	}
	return 0
}

func init() {
	proto.RegisterType((*WhitelistedContract)(nil), "aib.cron.v1beta1.WhitelistedContract")
}

func init() { proto.RegisterFile("aib/cron/v1beta1/cron.proto", fileDescriptor_6c83358d263c9e57) }

var fileDescriptor_6c83358d263c9e57 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4a, 0xc3, 0x30,
	0x18, 0xc7, 0x17, 0x9d, 0xd3, 0x05, 0xd4, 0x51, 0x05, 0x8b, 0x83, 0x30, 0x04, 0x61, 0x1e, 0x5c,
	0x28, 0x3e, 0xc1, 0xf4, 0x24, 0x82, 0x87, 0x21, 0x08, 0x5e, 0x4a, 0xda, 0x84, 0x2e, 0xd0, 0x24,
	0x25, 0xc9, 0x74, 0xf5, 0x29, 0x7c, 0x2c, 0x8f, 0x3b, 0x7a, 0x94, 0x16, 0xdf, 0x43, 0x92, 0xac,
	0xe8, 0x2d, 0xdf, 0xff, 0xfb, 0xf3, 0xfb, 0x85, 0x0f, 0x8e, 0x09, 0xcf, 0x70, 0xae, 0x95, 0xc4,
	0xaf, 0x49, 0xc6, 0x2c, 0x49, 0xfc, 0x30, 0xab, 0xb4, 0xb2, 0x2a, 0x1a, 0x11, 0x9e, 0xcd, 0xfc,
	0xbc, 0x5d, 0x9e, 0x9f, 0x16, 0xaa, 0x50, 0x7e, 0x89, 0xdd, 0x2b, 0xf4, 0x2e, 0x7e, 0x00, 0x3c,
	0x79, 0x5e, 0x72, 0xcb, 0x4a, 0x6e, 0x2c, 0xa3, 0x77, 0x4a, 0x5a, 0x4d, 0x72, 0x1b, 0x9d, 0xc1,
	0xfd, 0x82, 0x08, 0x96, 0x72, 0x1a, 0x83, 0x09, 0x98, 0xf6, 0x17, 0x03, 0x37, 0xde, 0xd3, 0xe8,
	0x0a, 0x8e, 0x0c, 0xcb, 0x57, 0x9a, 0xdb, 0x3a, 0x25, 0x94, 0x6a, 0x66, 0x4c, 0xbc, 0x33, 0x01,
	0xd3, 0xe1, 0xe2, 0xb8, 0xcb, 0xe7, 0x21, 0x8e, 0x2e, 0xe1, 0x51, 0xbe, 0xe5, 0xa5, 0x84, 0x0a,
	0x2e, 0xe3, 0x5d, 0x5f, 0x3c, 0xec, 0xd2, 0xb9, 0x0b, 0xa3, 0x31, 0x1c, 0x7a, 0x95, 0x24, 0x82,
	0xc5, 0x7d, 0xdf, 0x38, 0x70, 0xc1, 0x23, 0x11, 0xcc, 0xe9, 0xfe, 0x31, 0x82, 0x6e, 0x2f, 0xe8,
	0xfe, 0x28, 0x41, 0xd7, 0x71, 0x6c, 0x5d, 0xb1, 0x78, 0xe0, 0x3f, 0xed, 0x39, 0x4f, 0x75, 0xc5,
	0x6e, 0x1f, 0x3e, 0x1b, 0x04, 0x36, 0x0d, 0x02, 0xdf, 0x0d, 0x02, 0x1f, 0x2d, 0xea, 0x6d, 0x5a,
	0xd4, 0xfb, 0x6a, 0x51, 0xef, 0x25, 0x29, 0xb8, 0x5d, 0xae, 0xb2, 0x59, 0xae, 0x04, 0xa6, 0xb5,
	0x60, 0xd2, 0x70, 0x25, 0xd7, 0xf5, 0x3b, 0xd6, 0xaa, 0x2c, 0x49, 0x55, 0x5d, 0xbf, 0x11, 0x23,
	0xf0, 0x3a, 0x5c, 0xda, 0xb1, 0x4d, 0x36, 0xf0, 0xb7, 0xbb, 0xf9, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0x06, 0x2e, 0x2a, 0x89, 0x82, 0x01, 0x00, 0x00,
}

func (m *WhitelistedContract) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WhitelistedContract) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WhitelistedContract) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.GameType != 0 {
		i = encodeVarintCron(dAtA, i, uint64(m.GameType))
		i--
		dAtA[i] = 0x30
	}
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintCron(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.GameName) > 0 {
		i -= len(m.GameName)
		copy(dAtA[i:], m.GameName)
		i = encodeVarintCron(dAtA, i, uint64(len(m.GameName)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ContractAdmin) > 0 {
		i -= len(m.ContractAdmin)
		copy(dAtA[i:], m.ContractAdmin)
		i = encodeVarintCron(dAtA, i, uint64(len(m.ContractAdmin)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SecurityAddress) > 0 {
		i -= len(m.SecurityAddress)
		copy(dAtA[i:], m.SecurityAddress)
		i = encodeVarintCron(dAtA, i, uint64(len(m.SecurityAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.GameId != 0 {
		i = encodeVarintCron(dAtA, i, uint64(m.GameId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintCron(dAtA []byte, offset int, v uint64) int {
	offset -= sovCron(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *WhitelistedContract) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.GameId != 0 {
		n += 1 + sovCron(uint64(m.GameId))
	}
	l = len(m.SecurityAddress)
	if l > 0 {
		n += 1 + l + sovCron(uint64(l))
	}
	l = len(m.ContractAdmin)
	if l > 0 {
		n += 1 + l + sovCron(uint64(l))
	}
	l = len(m.GameName)
	if l > 0 {
		n += 1 + l + sovCron(uint64(l))
	}
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovCron(uint64(l))
	}
	if m.GameType != 0 {
		n += 1 + sovCron(uint64(m.GameType))
	}
	return n
}

func sovCron(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCron(x uint64) (n int) {
	return sovCron(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *WhitelistedContract) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCron
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WhitelistedContract: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WhitelistedContract: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GameId", wireType)
			}
			m.GameId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCron
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GameId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecurityAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCron
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCron
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCron
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SecurityAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAdmin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCron
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCron
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCron
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAdmin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GameName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCron
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCron
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCron
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GameName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCron
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCron
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCron
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GameType", wireType)
			}
			m.GameType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCron
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GameType |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipCron(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCron
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCron(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCron
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCron
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCron
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCron
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCron
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCron
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCron        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCron          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCron = fmt.Errorf("proto: unexpected end of group")
)
