name: Build Rollapp-wasm
on: ["push"]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
        targetos: [darwin, linux]
        go-version: ['1.21.x']
        include:
          - targetos: darwin
            arch: arm64
    name: rollapp ${{ matrix.arch }} for ${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4.1.0
        with:
          go-version: ${{ matrix.go-version }}
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

      - name: Compile rollapp-wasm
        run: |
          go mod download
          cd rollappd
          go build .

      - uses: actions/upload-artifact@v4
        with:
          name: rollappd ${{ matrix.targetos }} ${{ matrix.arch }}
          path: rollappd/rollappd
